name: CI

on:
  push:
    branches:
    - master
    - releases/*
    tags:
    - v*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        test: ["inmem", "mssql", "mssql-v3", "mysql", "postgres", "sqlite", "hal", "http"]

    runs-on: ubuntu-latest
    name: Test ${{ matrix.test }}
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
          - 11433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: E@syP@ssw0rd
        options: --name sql-stream-store-tests-mssql
      mysql:
        image: mysql:5.6
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD=1: 1
        options: --name sql-stream-store-tests-mysql
      postgres:
        image: postgres:10.4-alpine
        ports:
          - 5432:5432
        options: --name sql-stream-store-tests-postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pull Containers
        shell: bash
        run: docker pull damianh/dotnet-core-lts-sdks:1
      - name: Build and Test
        shell: bash
        run: ./build.sh test-${{ matrix.test }}
  publish:
    runs-on: ubuntu-latest
    needs: build
    name: Publish
    env:
      FEEDZ_SSS_API_KEY: ${{secrets.FEEDZ_SSS_API_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Package and Publish
        shell: bash
        run: ./build.sh publish
