name: CI

on:
  push:
    branches:
    - master
    - releases/*
    tags:
    - v*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        test: ["inmem", "postgres"]

    runs-on: ubuntu-latest
    name: Test ${{ matrix.test }}
    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --name sql-stream-store-tests-postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pull Containers
        shell: bash
        run: docker pull alpinelinux/docker-cli:latest-x86_64
      - name: Build and Test
        shell: bash
        run: ./build.sh test-${{ matrix.test }}
  publish:
    runs-on: ubuntu-latest
    needs: build
    name: Publish
    env:
      FEEDZ_SSS_API_KEY: ${{secrets.FEEDZ_SSS_API_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Package and Publish
        shell: bash
        run: ./build.sh publish
